<?php
declare(strict_types=1);

namespace App\Services;

/**
 * The single source of truth for final_status (Part 16.6).
 *
 * arrival_status and departure_status are two independent facts about a
 * student's classroom visit; final_status is the reportable value derived from
 * them. Deriving it in one place — never inline at the call site — is what
 * keeps the attendance table, the live feed, the dashboards and six different
 * report types from quietly disagreeing about what "Incomplete" means.
 */
final class AttendanceStatusResolver
{
    // arrival_status
    public const ARRIVAL_PRESENT            = 'present';
    public const ARRIVAL_LATE               = 'late';
    public const ARRIVAL_ABSENT             = 'absent';
    public const ARRIVAL_EXCUSED            = 'excused';
    public const ARRIVAL_OFFICIAL_BUSINESS  = 'official_business';

    // departure_status
    public const DEPARTURE_PENDING     = 'pending';
    public const DEPARTURE_TIMED_OUT   = 'timed_out';
    public const DEPARTURE_LEFT_EARLY  = 'left_early';
    public const DEPARTURE_NO_TIME_OUT = 'no_time_out';
    public const DEPARTURE_AUTO_CLOSED = 'auto_closed';

    // final_status
    public const FINAL_PRESENT           = 'Present';
    public const FINAL_LATE              = 'Late';
    public const FINAL_ABSENT            = 'Absent';
    public const FINAL_EXCUSED           = 'Excused';
    public const FINAL_OFFICIAL_BUSINESS = 'Official Business';
    public const FINAL_INCOMPLETE        = 'Incomplete';
    public const FINAL_LEFT_EARLY        = 'Left Early';

    /**
     * Resolve the reportable status.
     *
     * The mapping follows the table in Part 16.6 exactly. An auto-closed
     * departure keeps the arrival status (a student who was present and simply
     * never tapped out at a session the system closed for them was still
     * present); a genuinely missing tap-out with auto-close disabled is
     * Incomplete, which is the honest answer.
     */
    public static function resolve(string $arrivalStatus, string $departureStatus): string
    {
        // Non-attending arrival states have no departure component at all.
        return match ($arrivalStatus) {
            self::ARRIVAL_ABSENT            => self::FINAL_ABSENT,
            self::ARRIVAL_EXCUSED           => self::FINAL_EXCUSED,
            self::ARRIVAL_OFFICIAL_BUSINESS => self::FINAL_OFFICIAL_BUSINESS,
            default                          => self::resolveAttending($arrivalStatus, $departureStatus),
        };
    }

    private static function resolveAttending(string $arrivalStatus, string $departureStatus): string
    {
        $base = $arrivalStatus === self::ARRIVAL_LATE ? self::FINAL_LATE : self::FINAL_PRESENT;

        return match ($departureStatus) {
            self::DEPARTURE_LEFT_EARLY  => self::FINAL_LEFT_EARLY,
            self::DEPARTURE_NO_TIME_OUT => self::FINAL_INCOMPLETE,
            // Still in the room: the record reads as its arrival status until
            // the session closes and the departure is settled one way or another.
            self::DEPARTURE_PENDING     => $base,
            self::DEPARTURE_TIMED_OUT,
            self::DEPARTURE_AUTO_CLOSED => $base,
            default                     => $base,
        };
    }

    /**
     * Display label including the auto-close qualifier the spec asks reports to
     * show: "Present (Auto-Closed)".
     */
    public static function label(string $finalStatus, string $departureStatus, bool $autoGenerated = false): string
    {
        if ($autoGenerated || $departureStatus === self::DEPARTURE_AUTO_CLOSED) {
            if ($finalStatus === self::FINAL_PRESENT || $finalStatus === self::FINAL_LATE) {
                return $finalStatus . ' (Auto-Closed)';
            }
        }

        return $finalStatus;
    }

    /** Does this status count towards the attendance percentage? */
    public static function countsAsPresent(string $finalStatus): bool
    {
        return in_array($finalStatus, [
            self::FINAL_PRESENT,
            self::FINAL_LATE,
            self::FINAL_LEFT_EARLY,
            self::FINAL_INCOMPLETE,
            self::FINAL_EXCUSED,
            self::FINAL_OFFICIAL_BUSINESS,
        ], true);
    }

    /** Statuses that mean the student was physically in the room. */
    public static function countsAsAttended(string $finalStatus): bool
    {
        return in_array($finalStatus, [
            self::FINAL_PRESENT,
            self::FINAL_LATE,
            self::FINAL_LEFT_EARLY,
            self::FINAL_INCOMPLETE,
        ], true);
    }

    /** @return list<string> */
    public static function allFinalStatuses(): array
    {
        return [
            self::FINAL_PRESENT,
            self::FINAL_LATE,
            self::FINAL_LEFT_EARLY,
            self::FINAL_INCOMPLETE,
            self::FINAL_ABSENT,
            self::FINAL_EXCUSED,
            self::FINAL_OFFICIAL_BUSINESS,
        ];
    }

    /** @return list<string> */
    public static function allArrivalStatuses(): array
    {
        return [
            self::ARRIVAL_PRESENT,
            self::ARRIVAL_LATE,
            self::ARRIVAL_ABSENT,
            self::ARRIVAL_EXCUSED,
            self::ARRIVAL_OFFICIAL_BUSINESS,
        ];
    }

    /** @return list<string> */
    public static function allDepartureStatuses(): array
    {
        return [
            self::DEPARTURE_PENDING,
            self::DEPARTURE_TIMED_OUT,
            self::DEPARTURE_LEFT_EARLY,
            self::DEPARTURE_NO_TIME_OUT,
            self::DEPARTURE_AUTO_CLOSED,
        ];
    }

    /**
     * How an arrival reads to a person.
     *
     * The column stores `present`, which is the opposite of `absent` — but the
     * question the column actually answers is whether the student got here in
     * time, and next to a `late` in the row below, "present" reads as though it
     * is describing something else entirely. "on time" is the same fact said in
     * the terms the reader is comparing.
     */
    public static function arrivalLabel(string $arrivalStatus): string
    {
        return match ($arrivalStatus) {
            self::ARRIVAL_PRESENT           => 'on time',
            self::ARRIVAL_LATE              => 'late',
            self::ARRIVAL_ABSENT            => 'absent',
            self::ARRIVAL_EXCUSED           => 'excused',
            self::ARRIVAL_OFFICIAL_BUSINESS => 'official business',
            default                          => str_replace('_', ' ', $arrivalStatus),
        };
    }

    /**
     * Colour for an arrival.
     *
     * Deliberately harder than the final-status palette, where Late is amber.
     * A final status is a summary of the whole meeting and amber says "not
     * clean, look closer". An arrival is one yes-or-no question asked at one
     * moment — the student was here in time or was not — so it is green or red
     * with nothing in between.
     */
    public static function arrivalClass(string $arrivalStatus): string
    {
        return match ($arrivalStatus) {
            self::ARRIVAL_PRESENT           => 'text-success',
            self::ARRIVAL_LATE              => 'text-danger',
            self::ARRIVAL_ABSENT            => 'text-danger',
            self::ARRIVAL_EXCUSED           => 'text-info',
            self::ARRIVAL_OFFICIAL_BUSINESS => 'text-info',
            default                          => 'text-muted',
        };
    }

    /** The same two-colour split as arrivalClass(), for tables that use badges. */
    public static function arrivalBadgeClass(string $arrivalStatus): string
    {
        return match ($arrivalStatus) {
            self::ARRIVAL_PRESENT           => 'badge-success',
            self::ARRIVAL_LATE              => 'badge-danger',
            self::ARRIVAL_ABSENT            => 'badge-danger',
            self::ARRIVAL_EXCUSED           => 'badge-info',
            self::ARRIVAL_OFFICIAL_BUSINESS => 'badge-info',
            default                          => 'badge-neutral',
        };
    }

    public static function badgeClass(string $finalStatus): string
    {
        return match ($finalStatus) {
            self::FINAL_PRESENT           => 'badge-success',
            self::FINAL_LATE              => 'badge-warning',
            self::FINAL_LEFT_EARLY        => 'badge-warning',
            self::FINAL_INCOMPLETE        => 'badge-warning',
            self::FINAL_ABSENT            => 'badge-danger',
            self::FINAL_EXCUSED           => 'badge-info',
            self::FINAL_OFFICIAL_BUSINESS => 'badge-info',
            default                        => 'badge-neutral',
        };
    }
}
